baseurl = "http://cdax.github.io/"
languageCode = "en-us"
title = "Chitharanjan's Blog"
theme = "phantasm"
canonifyurls = true

[params]
name = "Chitharanjan Das"
author = "Chitharanjan Das"
aboutAuthor = "Software Developer"
logoPath = "phantasm-logo-3x.png"
avatarPath = "avatar.jpg"
bio = "Software Developer"
email = "das.chitharanjan@gmail.com"
copyright = "© 2018, Chitharanjan Das"
tag = "tags"
